name    'kinneygroup-splunkforwarder'
version '0.1.0'
source 'https://github.com/kinneygroup/puppet-module-splunkforwarder.git'
author 'Kinney Group'
license 'Apache License, Version 2.0'
summary 'Puppet module to install and configure Splunk Universal Forwarder'
description 'Puppet module to install and configure Splunk Universal Forwarder'
project_page 'https://github.com/kinneygroup/puppet-module-splunkforwarder'
