name    'martezr-splunkforwarder'
version '0.1.0'
source 'https://github.com/martezr/puppet-splunkforwarder.git'
author 'Martez Reed'
license 'Apache License, Version 2.0'
summary 'Puppet module to install and configure Splunk Universal Forwarder'
description 'Puppet module to install and configure Splunk Universal Forwarder'
project_page 'https://github.com/martezr/puppet-splunkforwarder'